### ISSUE TITLE
Cenarion Circle reputation not parsing correctly

### ISSUE THREAD

**Issue by mhhuijsmans** [Road-block/Reputable#7]
![image](https://user-images.githubusercontent.com/8067852/200203280-6a1035f8-1773-4cbe-933b-a2cae09ea9d4.png)

**Comment by Road-block** [comment]
There's no way that's the only / first error.
Parses fine for me.
![reputable-cc](https://user-images.githubusercontent.com/109839/200204101-4a511d01-863b-416c-a6f2-b697b244f3d9.png)

**Comment by mhhuijsmans** [comment]
I am not getting any errors whatsoever, disabled every addon except for this one and it still doesn't work. Cenarion Circle is the only one not working.

**Comment by Road-block** [comment]
Hmm.. I wonder. 
I did some minor cleanup that's not pushed, since the addon _kinda has a new author_ in Schoppi, was waiting to see if he does an update.

Try this and see if it makes a difference.
[Reputable-1.36-test.zip](https://github.com/Road-block/Reputable/files/9947484/Reputable-1.36-test.zip)

**Comment by mhhuijsmans** [comment]
That fixed it for me :)
